name: eff-ph
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anndata=0.9.1
  - appdirs=1.4.4
  - arpack=3.7.0
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.1.2
  - contourpy=1.0.5
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dbus=1.13.18
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.4.9
  - giflib=5.2.1
  - glib=2.70.2
  - h5py=3.7.0
  - hdf5=1.10.6
  - icu=68.2
  - idna=3.4
  - igraph=0.9.7
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.12.2
  - jedi=0.18.1
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - leidenalg=0.8.9
  - llvmlite=0.39.1
  - locket=1.0.0
  - lz4-c=1.9.4
  - matplotlib=3.7.0
  - matplotlib-base=3.7.0
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mscorefonts=0.0.1
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=2.8.4
  - nss=3.74
  - numba=0.56.4
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - opentsne=0.6.2
  - pandas=1.5.3
  - parso=0.8.3
  - partd=1.2.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=23.2.1
  - pooch=1.4.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygobject=3.42.0
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pyqt5-sip=4.19.18
  - pysocks=1.7.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - python-igraph=0.9.9
  - pytorch=1.13.1=py3.10_cuda11.6_cudnn8.3.2_0
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7
  - pywavelets=1.4.1
  - pyyaml=6.0
  - readline=8.2
  - requests=2.31.0
  - scanpy=1.9.3
  - scikit-image=0.19.3
  - scikit-learn=1.2.1
  - scikit-misc=0.1.4
  - scipy=1.10.0
  - seaborn=0.12.2
  - setuptools=68.0.0
  - six=1.16.0
  - stack_data=0.2.0
  - threadpoolctl=2.2.0
  - tifffile=2020.6.3
  - tk=8.6.12
  - toolz=0.12.0
  - torchvision=0.14.1
  - traitlets=5.7.1
  - urllib3=1.26.16
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xz=5.2.10
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.5.2
  - umap-learn=0.5.4
  - pip:
      - annoy==1.17.3
      - cython==0.29.33
      - glasbey==0.2.0
      - pybind11==2.10.3
      - pykeops==2.1.1
      - pynndescent==0.5.10
      - scanorama==1.7.3
      - scikit-tda==1.0.0
      - sortedcontainers==2.4.0
      - tadasets==0.0.4
      - tqdm==4.65.0

